File = open("Vibrio_cholerae.txt", "r")
Text = str(File.read())
#Text = "AGTCATCCACAGCAATCACTTCATCGGCATGACGAATTTGCACACCTTTGCTCAGTTGATCGAGCGCGCAAAGTGACATGTTCTCTTTCACCGAAAGACCGAGTACCAAGCCATCGCCTTTACGATCTTCAGAAATATAGGCGATGCCATTGGCCAAACCATCTTGCGGACTGACAGGGTTAACCGTGCGCCCGTTGAGGTTAATCACGCCACGCTCCGAAGGGAGCGCGCCATAAATCACCTTCATCAGTTCAGTGCGCCCAGCCCCCATCAGGCCAGAGACACCAAGAATCTCGCCTTTTTTAAGCGTAAAGCTGACATCGTGCACACCCGAGCCAGTTAGGCCAATCACCTCAAGGCTGATGTCACCCTGCTGCGCGGCAATACGTGGGTACTGCTCTTCCAGTTTACGGCCAACCATCATCTCAATCAGGCCATCTTCATTGGTATCGCACACGCGGCACTCGCCAAT"
Pattern = "CTTGATCAT"


def PatternMatching(Text, Pattern):
    result = ""

    for i in range(0, len(Text) - len(Pattern) + 1):
        if Text[i: i + len(Pattern)] == Pattern:
            result = result + str(i) + " "

    return (result)


print(PatternMatching(Text, Pattern))